---

- name: install openvpn
  apt: pkg={{item}} update_cache=yes cache_valid_time=3600 install_recommends=no
  with_items:
    - openvpn

- include: configuration.yml
  when: openvpn_configs is defined
